from app.infrastructure.database.models.sales_department.manager_group import *
from app.infrastructure.database.models.sales_department.sales_department import *
from app.infrastructure.database.models.subscription.subscription import *
from app.infrastructure.database.models.tasks.manager_task import *
from app.infrastructure.database.models.technical_support.chat import *
from app.infrastructure.database.models.technical_support.ticket import *
from app.infrastructure.database.models.users.admin import *
from app.infrastructure.database.models.users.client import *
from app.infrastructure.database.models.users.manager import *
from app.infrastructure.database.models.users.supervisor import *
