"""init

Revision ID: 0f4002498769
Revises:
Create Date: 2023-12-15 14:45:20.103695

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0f4002498769'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'admin',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'chat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'client',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('first_name', sa.String(), nullable=False),
        sa.Column('last_name', sa.String(), nullable=False),
        sa.Column('phone_number', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=300), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'manager_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('supervisor_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'sales_department',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'supervisor',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('sales_department_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'ticket',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('problem', sa.String(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('close_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'manager',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('manager_group_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'subscription',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('kind', sa.String(), nullable=False),
        sa.Column('price', sa.Numeric(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'manager_task',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('delegated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('manager_id', sa.Integer(), nullable=False),
        sa.Column('delegated_by_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'message',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('manager_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )

    op.create_foreign_key(
        constraint_name='chat_client_id_fk_client',
        source_table='chat',
        referent_table='client',
        local_cols=['client_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='manager_group_supervisor_id_fk_supervisor',
        source_table='manager_group',
        referent_table='supervisor',
        local_cols=['supervisor_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='supervisor_sales_department_id_fk_sales_department',
        source_table='supervisor',
        referent_table='sales_department',
        local_cols=['sales_department_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='ticket_client_id_fk_client',
        source_table='ticket',
        referent_table='client',
        local_cols=['client_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='manager_manager_group_id_fk_manager_group',
        source_table='manager',
        referent_table='manager_group',
        local_cols=['manager_group_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='subscription_client_id_fk_client',
        source_table='subscription',
        referent_table='client',
        local_cols=['client_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='manager_task_delegated_by_id_fk_supervisor',
        source_table='manager_task',
        referent_table='supervisor',
        local_cols=['delegated_by_id'],
        remote_cols=['id'],
    )
    op.create_foreign_key(
        constraint_name='manager_task_manager_id_fk_manager',
        source_table='manager_task',
        referent_table='manager',
        local_cols=['manager_id'],
        remote_cols=['id'],
    )

    op.create_foreign_key(
        constraint_name='message_chat_id_fk_chat',
        source_table='message',
        referent_table='chat',
        local_cols=['chat_id'],
        remote_cols=['id'],
    )
    op.create_foreign_key(
        constraint_name='message_client_id_fk_client',
        source_table='message',
        referent_table='client',
        local_cols=['client_id'],
        remote_cols=['id'],
    )
    op.create_foreign_key(
        constraint_name='message_manager_id_fk_manager',
        source_table='message',
        referent_table='manager',
        local_cols=['manager_id'],
        remote_cols=['id'],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('manager_task')
    op.drop_table('subscription')
    op.drop_table('manager')
    op.drop_table('ticket')
    op.drop_table('supervisor')
    op.drop_table('sales_department')
    op.drop_table('manager_group')
    op.drop_table('client')
    op.drop_table('chat')
    op.drop_table('admin')
    # ### end Alembic commands ###
